config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  scope :most_reviews, -> {(
    select("products.name, products.id, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(5)
  )}

  scope :most_recent, -> { order(created_at: :desc).limit(3) }

  scope :from_usa, -> { where(country: 'USA')}
  scope :from_usa, -> { where(country: 'United States')}
  scope :from_usa, -> { where(country: 'America')}
  scope :from_usa, -> { where(country: 'US')}
  scope :from_usa, -> { where(country: 'U.S.A')}
  scope :from_usa, -> { where(country: 'Unites States of America')}

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates :content, presence: true, length: {minimum: 50, maximum: 250}
  validates :rating, :presence => true
  validates :rating, :inclusion => 1..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @review_products = Product.most_reviews
    @recent_products = Product.most_recent
    @usa_products = Product.from_usa
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :country)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
  @product = Product.find(params[:product_id])
  @review = @product.reviews.new(review_params)
  if @review.save
    flash[:notice] = "Review added!"
    redirect_to product_path(@review.product)
  else
    render :new
  end
end

private
  def review_params
  params.require(:review).permit(:author, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbertaCoOp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Asap+Condensed" rel="stylesheet">
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :cost %>
  <br>
  <%= f.number_field :cost %>
  <br>
  <%= f.label :country %>
  <br>
  <%= f.text_field :country %>
  <br>
  <br>
  <%= f.submit  %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render "form" %>
<hr>

app/views/products/index.html.erb
<h1>Alberta Food Co-Op</h1>

<%= image_tag "grocery.jpg" %>
<br>
<br>

<div class="col-md-6">
<h2>Products we sell</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<h2><%= link_to "Add a New Product", new_product_path %></h2>
<br>
</div>

<div class="column col md-4">
<h2>Recently Added</h2>
  <hr>
  <ul>
    <% @recent_products.each do |product|%>
      <li><%= link_to product.name, product_path(product)%><br>
    <%end%>
  </ul>
  <br>
  <h2>Most Reviewed</h2>
  <hr>
  <ul>
    <% @review_products.each do |product|%>
      <li><%= link_to product.name, product_path(product)%><br>
    <%end%>
  </ul>
  <br>
  <h2>Products from the USA</h2>
  <hr>
  <% if @usa_products.any? %>
  <ul>
  <% @usa_products.each do |product|%>
    <li><%= link_to product.name, product_path(product)%><br>
  <%end%>
  </ul>
    <% else %>
    <p>There are no American products yet!</p>
    <% end %>
  <br>
  <br>
</div>

app/views/products/new.html.erb
<h1>New product:</h1>
<%= render "form" %>
<hr>

app/views/products/show.html.erb
<h1><%= @product.name %>, <%= @product.country %></h1>
<h3>$<%= @product.cost %></h3>

<ul>
  <li><%= link_to "Add a review", new_product_review_path(@product) %></li>
  <li><%= link_to "Edit Product Information", edit_product_path(@product) %></li>
  <li><%= link_to "Delete Product", product_path(@product),
                           :data => {:confirm => "You sure?",
                                     :method => "delete"} %></li>
</ul>

<% if @product.reviews.any? %>
  <h2>Reviews:</h2>
  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        Rating: <%= review.rating %>
        <br>
        Comments: "<%= review.content %>"
        <br>
        Author: <%= review.author %>
      </li>
      <br>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <br>
  <%= f.text_field :author %>
  <br>
  <%= f.label :content %>
  <br>
  <%= f.text_field :content %>
  <br>
  <%= f.label :rating %>
  <br>
  <%= f.number_field :rating %>
  <br>
  <br>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>
<%= render 'form' %>
<hr>